import {
  MOCK_ANALYSES,
  MOCK_REPORTS,
  MOCK_CHAT_MESSAGES,
  MOCK_DRUGS,
  MOCK_ADMIN_STATS,
  MOCK_MODELS,
  MOCK_CHEST_XRAY_SVG,
} from '@/lib/mocks/data';
import {
  AnalysisItem,
  ReportItem,
  ChatMessage,
  DrugInfo,
  UserProfile,
  AdminStats,
  ModelMetric,
  ScanType,
  BodyRegion,
} from '@/types';
import { createClient as createSupabaseClient } from '@/lib/supabase/client';

const delay = (ms = 400) => new Promise((res) => setTimeout(res, ms));

class MediLensApiService {
  private analyses: AnalysisItem[] = [...MOCK_ANALYSES];
  private reports: ReportItem[] = [...MOCK_REPORTS];
  private chatMessages: ChatMessage[] = [...MOCK_CHAT_MESSAGES];

  async getAnalyses(): Promise<AnalysisItem[]> {
    await delay(350);
    return [...this.analyses];
  }

  async getAnalysisById(id: string): Promise<AnalysisItem | null> {
    await delay(300);
    const found = this.analyses.find((item) => item.id === id);
    return found ? { ...found } : null;
  }

  async createAnalysis(data: {
    title: string;
    patientId: string;
    patientAge?: number;
    patientGender?: 'Male' | 'Female' | 'Other';
    scanType: ScanType;
    bodyRegion: BodyRegion;
    imageUrl?: string;
  }): Promise<AnalysisItem> {
    await delay(800);
    const newId = `scan-${Date.now().toString().slice(-6)}`;
    const newAnalysis: AnalysisItem = {
      id: newId,
      title: data.title || `${data.scanType} Scan`,
      patientId: data.patientId || `PT-${Math.floor(10000 + Math.random() * 90000)}`,
      patientAge: data.patientAge || 45,
      patientGender: data.patientGender || 'Female',
      scanType: data.scanType,
      bodyRegion: data.bodyRegion,
      status: 'Completed',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      imageUrl: data.imageUrl || MOCK_CHEST_XRAY_SVG,
      thumbnailUrl: data.imageUrl || MOCK_CHEST_XRAY_SVG,
      overallPrediction: `Focal Signal Alteration in ${data.bodyRegion}`,
      overallConfidence: 0.923,
      modelVersion: `MediVision-${data.scanType.replace(/\s+/g, '')} v2.5`,
      predictionDistribution: [
        { label: 'Suspicious Focal Area', percentage: 92.3 },
        { label: 'Normal Baseline', percentage: 5.6 },
        { label: 'Artifact / Other', percentage: 2.1 },
      ],
      heatmapData: { hotspots: [{ x: 55, y: 48, radius: 70, intensity: 0.91, label: 'High Confidence Region' }] },
      findings: [{
        id: `f-${Date.now()}`,
        name: 'Primary Focal Abnormality Detected',
        confidence: 0.923,
        severity: 'Moderate',
        location: `${data.bodyRegion} region`,
        explanation: 'Deep learning spatial heatmaps show concentrated attention intensity in this zone.',
        clinicalSignificance: 'Correlate with acute patient clinical presentation.',
        boundingBox: { x: 45, y: 40, width: 22, height: 20 },
      }],
      recommendations: ['Review findings with attending clinician.', 'Consider complementary multi-planar evaluation if symptoms persist.'],
    };
    this.analyses.unshift(newAnalysis);
    return newAnalysis;
  }

  async getReports(): Promise<ReportItem[]> { await delay(350); return [...this.reports]; }

  async getReportById(id: string): Promise<ReportItem | null> {
    await delay(250);
    const report = this.reports.find((r) => r.id === id);
    return report ? { ...report } : null;
  }

  async generateReport(analysisId: string): Promise<ReportItem> {
    await delay(700);
    const analysis = await this.getAnalysisById(analysisId);
    const user = await this.getUserProfile();
    const newReport: ReportItem = {
      id: `rep-${Date.now().toString().slice(-5)}`,
      analysisId,
      title: `AI Diagnostic Summary Report - ${analysis?.title || 'Scan'}`,
      patientId: analysis?.patientId || 'PT-99999',
      scanType: analysis?.scanType || 'Chest X-Ray',
      date: new Date().toISOString(),
      status: 'Finalized',
      radiologistName: `${user.name} (${user.role})`,
      summary: `Automated assessment of ${analysis?.scanType} indicates ${analysis?.overallPrediction} with ${((analysis?.overallConfidence || 0.9) * 100).toFixed(1)}% model confidence score.`,
      detailedFindings: analysis?.findings.map((f, i) => `${i + 1}. ${f.name} (${f.severity} Severity): ${f.explanation}`).join('\n\n') || 'No major findings recorded.',
      impression: analysis?.overallPrediction || 'Primary abnormality identified.',
      recommendations: analysis?.recommendations || ['Follow up with specialist.'],
      disclaimer: 'This automated document is generated by MediLens AI for diagnostic assistance only and does not replace certified professional radiology evaluation.',
    };
    this.reports.unshift(newReport);
    return newReport;
  }

  async getChatMessages(): Promise<ChatMessage[]> { await delay(200); return [...this.chatMessages]; }

  async sendChatMessage(content: string): Promise<ChatMessage> {
    await delay(300);
    const userMsg: ChatMessage = { id: `msg-${Date.now()}`, sender: 'user', content, timestamp: new Date().toISOString() };
    this.chatMessages.push(userMsg);
    await delay(800);
    const aiMsg: ChatMessage = {
      id: `msg-${Date.now() + 1}`,
      sender: 'assistant',
      content: 'Based on clinical imaging literature, always correlate AI-assisted findings with the patient clinical context and prior studies.',
      timestamp: new Date().toISOString(),
      sources: [{ title: 'ACR Appropriate Criteria', snippet: 'Guidelines on clinical imaging indications and standardized diagnostic terminology.' }],
    };
    this.chatMessages.push(aiMsg);
    return aiMsg;
  }

  async getDrugs(): Promise<DrugInfo[]> { await delay(300); return [...MOCK_DRUGS]; }
  async scanDrugByImage(_imagePreview: string): Promise<DrugInfo> { await delay(1200); return MOCK_DRUGS[0]; }

  async getUserProfile(): Promise<UserProfile> {
    await delay(100);
    const supabase = createSupabaseClient();
    const { data: { user }, error } = await supabase.auth.getUser();
    if (error || !user) throw new Error('Not authenticated');

    const role = user.user_metadata?.role as UserProfile['role'] | undefined;
    return {
      id: user.id,
      name: user.user_metadata?.full_name || user.email?.split('@')[0] || 'Authenticated User',
      email: user.email || '',
      role: role && ['Radiologist', 'Physician', 'Medical Student', 'Administrator'].includes(role) ? role : 'Physician',
      hospital: user.user_metadata?.hospital || '',
      avatarUrl: user.user_metadata?.avatar_url || '',
      memberSince: user.created_at ? new Date(user.created_at).toLocaleDateString('en-US', { month: 'long', year: 'numeric' }) : '',
    };
  }

  async updateUserProfile(updates: Partial<UserProfile>): Promise<UserProfile> {
    const supabase = createSupabaseClient();
    const { data: { user }, error } = await supabase.auth.getUser();
    if (error || !user) throw new Error('Not authenticated');

    const { data, error: updateError } = await supabase.auth.updateUser({
      data: {
        full_name: updates.name,
        role: updates.role,
        hospital: updates.hospital,
        avatar_url: updates.avatarUrl,
      },
    });
    if (updateError || !data.user) throw updateError || new Error('Failed to update profile');
    return this.getUserProfile();
  }

  async getAdminStats(): Promise<AdminStats> { await delay(300); return { ...MOCK_ADMIN_STATS }; }
  async getModels(): Promise<ModelMetric[]> { await delay(300); return [...MOCK_MODELS]; }
}

export const apiService = new MediLensApiService();
