import {
  MOCK_ANALYSES,
  MOCK_REPORTS,
  MOCK_CHAT_MESSAGES,
  MOCK_DRUGS,
  MOCK_USER,
  MOCK_ADMIN_STATS,
  MOCK_MODELS,
  MOCK_CHEST_XRAY_SVG,
} from '@/lib/mocks/data';
import {
  AnalysisItem,
  ReportItem,
  ChatMessage,
  DrugInfo,
  UserProfile,
  AdminStats,
  ModelMetric,
  ScanType,
  BodyRegion,
} from '@/types';

// Simulate realistic network delay (ms)
const delay = (ms = 400) => new Promise((res) => setTimeout(res, ms));

class MediLensApiService {
  private analyses: AnalysisItem[] = [...MOCK_ANALYSES];
  private reports: ReportItem[] = [...MOCK_REPORTS];
  private chatMessages: ChatMessage[] = [...MOCK_CHAT_MESSAGES];
  private user: UserProfile = { ...MOCK_USER };

  // --- Analyses API ---
  async getAnalyses(): Promise<AnalysisItem[]> {
    await delay(350);
    return [...this.analyses];
  }

  async getAnalysisById(id: string): Promise<AnalysisItem | null> {
    await delay(300);
    const found = this.analyses.find((item) => item.id === id);
    return found ? { ...found } : null;
  }

  async createAnalysis(data: {
    title: string;
    patientId: string;
    patientAge?: number;
    patientGender?: 'Male' | 'Female' | 'Other';
    scanType: ScanType;
    bodyRegion: BodyRegion;
    imageUrl?: string;
  }): Promise<AnalysisItem> {
    await delay(800);
    const newId = `scan-${Date.now().toString().slice(-6)}`;
    const newAnalysis: AnalysisItem = {
      id: newId,
      title: data.title || `${data.scanType} Scan`,
      patientId: data.patientId || `PT-${Math.floor(10000 + Math.random() * 90000)}`,
      patientAge: data.patientAge || 45,
      patientGender: data.patientGender || 'Female',
      scanType: data.scanType,
      bodyRegion: data.bodyRegion,
      status: 'Completed',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      imageUrl: data.imageUrl || MOCK_CHEST_XRAY_SVG,
      thumbnailUrl: data.imageUrl || MOCK_CHEST_XRAY_SVG,
      overallPrediction: `Focal Signal Alteration in ${data.bodyRegion}`,
      overallConfidence: 0.923,
      modelVersion: `MediVision-${data.scanType.replace(/\s+/g, '')} v2.5`,
      predictionDistribution: [
        { label: 'Suspicious Focal Area', percentage: 92.3 },
        { label: 'Normal Baseline', percentage: 5.6 },
        { label: 'Artifact / Other', percentage: 2.1 },
      ],
      heatmapData: {
        hotspots: [
          { x: 55, y: 48, radius: 70, intensity: 0.91, label: 'High Confidence Region' },
        ],
      },
      findings: [
        {
          id: `f-${Date.now()}`,
          name: 'Primary Focal Abnormality Detected',
          confidence: 0.923,
          severity: 'Moderate',
          location: `${data.bodyRegion} region`,
          explanation: 'Deep learning spatial heatmaps show concentrated attention intensity in this zone.',
          clinicalSignificance: 'Correlate with acute patient clinical presentation.',
          boundingBox: { x: 45, y: 40, width: 22, height: 20 },
        },
      ],
      recommendations: [
        'Review findings with attending clinician.',
        'Consider complementary multi-planar evaluation if symptoms persist.',
      ],
    };

    this.analyses.unshift(newAnalysis);
    return newAnalysis;
  }

  // --- Reports API ---
  async getReports(): Promise<ReportItem[]> {
    await delay(350);
    return [...this.reports];
  }

  async getReportById(id: string): Promise<ReportItem | null> {
    await delay(250);
    const report = this.reports.find((r) => r.id === id);
    return report ? { ...report } : null;
  }

  async generateReport(analysisId: string): Promise<ReportItem> {
    await delay(700);
    const analysis = await this.getAnalysisById(analysisId);
    const newReport: ReportItem = {
      id: `rep-${Date.now().toString().slice(-5)}`,
      analysisId: analysisId,
      title: `AI Diagnostic Summary Report - ${analysis?.title || 'Scan'}`,
      patientId: analysis?.patientId || 'PT-99999',
      scanType: analysis?.scanType || 'Chest X-Ray',
      date: new Date().toISOString(),
      status: 'Finalized',
      radiologistName: `${this.user.name} (${this.user.role})`,
      summary: `Automated assessment of ${analysis?.scanType} indicates ${analysis?.overallPrediction} with ${((analysis?.overallConfidence || 0.9) * 100).toFixed(1)}% model confidence score.`,
      detailedFindings: analysis?.findings.map((f, i) => `${i + 1}. ${f.name} (${f.severity} Severity): ${f.explanation}`).join('\n\n') || 'No major findings recorded.',
      impression: analysis?.overallPrediction || 'Primary abnormality identified.',
      recommendations: analysis?.recommendations || ['Follow up with specialist.'],
      disclaimer: 'This automated document is generated by MediLens AI for diagnostic assistance only and does not replace certified professional radiology evaluation.',
    };

    this.reports.unshift(newReport);
    return newReport;
  }

  // --- Assistant API ---
  async getChatMessages(): Promise<ChatMessage[]> {
    await delay(200);
    return [...this.chatMessages];
  }

  async sendChatMessage(content: string): Promise<ChatMessage> {
    await delay(300);
    const userMsg: ChatMessage = {
      id: `msg-${Date.now()}`,
      sender: 'user',
      content,
      timestamp: new Date().toISOString(),
    };
    this.chatMessages.push(userMsg);

    // Simulate AI Response synthesis
    await delay(800);
    const query = content.toLowerCase();
    let replyText = "Based on clinical imaging literature, findings with elevated AI confidence indicate localized density variation. Always evaluate patient clinical signs, inflammatory biomarkers (e.g. CRP/WBC), and prior diagnostic studies.";
    let sources = [
      {
        title: 'ACR Appropriate Criteria for Thoracic & Neuro Imaging',
        snippet: 'Guidelines on clinical imaging indications and standardized diagnostic terminology.',
      },
      {
        title: 'MediLens AI Explainability & Grad-CAM Whitepaper',
        snippet: 'Overview of neural heatmaps and feature localization in deep learning vision models.',
      },
    ];

    if (query.includes('finding') || query.includes('opacity') || query.includes('pneumonia')) {
      replyText = "Focal lung opacity on a radiograph signifies an area of increased radiodensity where air in the alveoli has been replaced by fluid, pus, or cellular debris. The most common etiology is lobar consolidation secondary to community-acquired pneumonia.";
    } else if (query.includes('mri') || query.includes('brain') || query.includes('tear')) {
      replyText = "On T2/FLAIR MRI sequences, hyperintense signals represent prolonged relaxation times typically caused by increased water content or edema. In musculoskeletal knee MRI, high signal extending to the meniscus articular surface indicates a tear.";
    } else if (query.includes('report') || query.includes('download')) {
      replyText = "You can preview and export the finalized clinical summary PDF by clicking the **Generate Report** button on any completed analysis screen or navigating to the **Reports** tab.";
    }

    const aiMsg: ChatMessage = {
      id: `msg-${Date.now() + 1}`,
      sender: 'assistant',
      content: replyText,
      timestamp: new Date().toISOString(),
      sources,
    };
    this.chatMessages.push(aiMsg);
    return aiMsg;
  }

  // --- Drug Scanner API ---
  async getDrugs(): Promise<DrugInfo[]> {
    await delay(300);
    return [...MOCK_DRUGS];
  }

  async scanDrugByImage(imagePreview: string): Promise<DrugInfo> {
    await delay(1200); // Simulate OCR & NLP lookup delay
    // Pick a random drug or default to Amoxicillin
    return MOCK_DRUGS[0];
  }

  // --- User & Admin API ---
  async getUserProfile(): Promise<UserProfile> {
    await delay(200);
    return { ...this.user };
  }

  async updateUserProfile(updates: Partial<UserProfile>): Promise<UserProfile> {
    await delay(400);
    this.user = { ...this.user, ...updates };
    return { ...this.user };
  }

  async getAdminStats(): Promise<AdminStats> {
    await delay(300);
    return { ...MOCK_ADMIN_STATS };
  }

  async getModels(): Promise<ModelMetric[]> {
    await delay(300);
    return [...MOCK_MODELS];
  }
}

export const apiService = new MediLensApiService();
